name: Trigger auto deployment for container-app-g2cda6iwonyvc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-g2cda6iwonyvc-AutoDeployTrigger-59d0a2f3-f394-4063-8561-0c6f43445ce9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPG2CDA6IWONYVC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPG2CDA6IWONYVC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPG2CDA6IWONYVC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryg2cda6iwonyvc.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPG2CDA6IWONYVC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPG2CDA6IWONYVC_REGISTRY_PASSWORD }}
          containerAppName: container-app-g2cda6iwonyvc
          resourceGroup: reactbasica2269acb
          imageToBuild: containerregistryg2cda6iwonyvc.azurecr.io/container-app-g2cda6iwonyvc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


